<?php
/* @var string $content
 * @var string $title */ ?>

<!doctype html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=yes, initial-scale=1.0, maximum-scale=5.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>MVC - <?= $title ?></title>
</head>
<body>
    <!-- Contenu dynamique -->
    <?= $content ?>
</body>
</html>